#OPERETION MODS
#python or matlab graph
PYTHON_GRAPH=False
GRAPH = True

FLIP_MOD=False
DELETE_MOD=True
MIXED=False

#count space as a mistake
COUNT_SPACE_MISS=False

#statistics
NUMBER_OF_STRINGS=2
# NUMBER_OF_STRINGS_MAX=10

NUMBER_OF_GOOD_STRINGS_FOR_FLIPS = 0
NUMBER_OF_GOOD_STRINGS_FOR_DELETIONS = 0
NUMBER_OF_GOOD_STRINGS_FOR_MIXED =0

NUMBER_OF_DELETIONS_IN_STR = 0
NUMBER_OF_DELETIONS_IN_STR_MAX=5
NUMBER_OF_FLIPS_IN_STR = 0
NUMBER_OF_FLIPS_IN_STR_MAX =5

NUMBER_OF_TOTAL_MISTAKES_MAX = 5
NUMBER_OF_TOTAL_MISTAKES_MIN = 0

STRING_GAP=1
DEL_GAP=1
FLIP_GAP=1
MIXED_GAP=1
RAPEAT_TIMES=3 #BORIS 25-10-18

