
#python or matlab graph
PYTHON_GRAPH = False
GRAPH = True

#OPERETION MODS
FLIP_MOD = False
DELETE_MOD = False
MIXED = False
RANDOM_DELETIONS=True

#count space as a mistake
COUNT_SPACE_MISS = False

NUMBER_OF_STRINGS_MIN = 2
NUMBER_OF_STRINGS_MAX = None

NUMBER_OF_DELETIONS_IN_STR_MIN = 0
NUMBER_OF_DELETIONS_IN_STR_MAX= 5
NUMBER_OF_FLIPS_IN_STR_MIN = 0
NUMBER_OF_FLIPS_IN_STR_MAX = 5

NUMBER_OF_TOTAL_MISTAKES_MAX = 5
NUMBER_OF_TOTAL_MISTAKES_MIN = 0



